#----------------------------------------------------------------
# AppVeyor configuration for R packages
#
# REFERENCES:
# * AppVeyor CI: https://ci.appveyor.com/
# * r-appveyor: https://github.com/krlmlr/r-appveyor
#
# Validate your .appveyor.yml file at
# https://ci.appveyor.com/tools/validate-yaml
#----------------------------------------------------------------
environment:
  _R_CHECK_FORCE_SUGGESTS_: false
  USE_RTOOLS: true
  
  matrix:
  - R_VERSION: devel
    R_ARCH: x64

  - R_VERSION: devel
    R_ARCH: i386

  - R_VERSION: release
    R_ARCH: x64


# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  ps: |
        Bootstrap
        InstallRtools

# Adapt as necessary starting from here

build_script:
  - echo Current directory=%CD%
  - travis-tool.sh install_r digest globals listenv markdown R.rsp

test_script:
  - travis-tool.sh run_tests

after_test:
  - 7z a all-Rout.zip *.Rcheck\**\*.Rout *.Rcheck\**\*.fail

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

  - path: all-Rout.zip
    name: AllRout

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip
