#----------------------------------------------------------------
# AppVeyor CI for R Packages
# https://github.com/krlmlr/r-appveyor
# Validator: https://ci.appveyor.com/tools/validate-yaml
#----------------------------------------------------------------
environment:
  _R_CHECK_FORCE_SUGGESTS_: false
  
  matrix:
  - R_VERSION: devel
    R_ARCH: x64

  - R_VERSION: devel
    R_ARCH: i386

  - R_VERSION: release
    R_ARCH: x64

init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  ps: |
        Bootstrap

cache:
  - C:\RLibrary -> appveyor.yml

build_script:
  - Rscript -e "c(physical = parallel::detectCores(logical = FALSE), logical = parallel::detectCores())"
  - echo Current directory=%CD%
  - travis-tool.sh install_r parallelly digest globals listenv markdown R.rsp
  
test_script:
  - travis-tool.sh run_tests

after_test:
  - 7z a all-Rout.zip *.Rcheck\**\*.Rout *.Rcheck\**\*.fail

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

  - path: all-Rout.zip
    name: AllRout

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip
